version: '2'

services:

  # Nginx as a load-balancing tier and reverse proxy
  nginx:
    build: nginx/
    mem_limit: 128m
    ports:
      - "80:80"     # nginx
      - "9090:9090" # telemetry
    links:
      - fortunes:fortunes
      - consul:consul
    environment:
      - SELF_HOST=localhost
      - CONSUL=consul
    restart: always
    command: >
      /usr/local/bin/containerpilot
      -config file:///etc/containerpilot/containerpilot.json
      nginx -g "daemon off;"

  # the Node.js application
  fortunes:
    build: fortunes/
    mem_limit: 128m
    ports:
      - "3000:3000" # node
      - "9091:9091" # telemetry
    links:
      - mysql:mysql
      - consul:consul
    environment:
      - SELF_HOST=localhost
      - CONSUL=consul
      - MYSQL_HOST=mysql
      - MYSQL_USER=me
      - MYSQL_PASSWORD=password1
      - MYSQL_DATABASE=mydb
    volumes:
      # we included these in our Docker build but we want to be able
      # to update them live in the workshop w/o imposing a rebuild
      - ./fortunes/test.js:/src/test.js
      - ./fortunes/fortunes.js:/src/fortunes.js
      - ./fortunes/sensor.js:/src/sensor.js
      - ./fortunes/prestart.js:/src/prestart.js
      - ./fortunes/lib:/src/lib
    restart: always
    command: >
      /bin/containerpilot
      -config file:///etc/containerpilot.json
      node /src/fortunes.js

  # database
  mysql:
    build: mysql/
    mem_limit: 256m
    ports:
      - "3306:3306" # mysql
      - "9092:9092" # telemetry
    links:
      - consul:consul
    environment:
      - SELF_HOST=localhost
      - CONSUL=consul
      - MYSQL_USER=me
      - MYSQL_PASSWORD=password1
      - MYSQL_REPL_USER=repl
      - MYSQL_REPL_PASSWORD=password2
      - MYSQL_DATABASE=mydb
      - INNODB_BUFFER_POOL_SIZE=128
      - INTERFACE=eth0
    restart: always

  # consul agent that will join the shared cluster
  consul:
    build: consul/
    mem_limit: 128m
    ports:
      - "8500:8500"
      - "53:53"
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8400:8400"
    environment:
      - SELF_HOST=localhost
      - CONSUL_HOST=localhost
    restart: always
    command: >-
      /usr/local/bin/containerpilot
      -config file:///etc/containerpilot.json
      /bin/consul agent -server -bootstrap
          -ui-dir /ui
          -data-dir=/data
          -config-dir=/etc/consul
