---
# This playbook deploys everything we need for the workshop VM environment.
# Assumes an Ubuntu VM with Python pre-installed (b/c Ansible requires Python)

- hosts: students
  remote_user: ubuntu
  become: true
  become_method: sudo

  tasks:
    - name: Update apt key
      apt_key: keyserver='hkp://p80.pool.sks-keyservers.net:80'
               id='58118E89F3A912897C070ADBF76221572C52609D'

    - name: Add docker.io repo
      apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main'
                      state=present

    - name: Update apt cache
      apt: update_cache=yes

    - name: Install docker
      apt: name=docker-engine state=installed

    - name: Give ubuntu user access to docker
      user: name=ubuntu groups=docker append=yes

    - name: Install emacs
      apt: name=emacs state=installed

    - name: Install pip
      apt: name=python-pip state=installed

    - name: Install Compose
      pip: name="docker-compose"

    - name: Add application
      git: repo=https://github.com/tgross/observability-workshop.git
           dest=/home/ubuntu/workshop
           update=yes
      become: false

    - name: Setup bash shell environment
      copy: src=.bash_profile
            dest=/home/ubuntu/.bash_profile
      become: false

    - name: Build docker containers
      command: docker-compose build
      args:
        chdir: workshop/

    - name: Update student ssh keys
      copy: src=keys/authorized_keys
            dest=/home/ubuntu/.ssh/authorized_keys
      become: false
